### ISSUE TITLE
Assertion fails in FlowIOOpenCVWrapper::write

### ISSUE THREAD

**Issue by serhangul** [davidstutz/flow-io-opencv#2]
Line 72 in the function `FlowIOOpenCVWrapper::write` should be changed from `assert(flow.type() == CV_32F)` to `assert(flow.type() == CV_32FC2)` , otherwise one gets the error `Assertion``flow.channels() == 2``failed.` while trying to write a flow file.

**Comment by davidstutz** [comment]
Yes, your are right - strange that I did not notice this earlier. Will fix it right away.

**Comment by davidstutz** [comment]
Ok, just as note: with OpenCV 2.4.9 it does not seem to be an issue.
