### ISSUE TITLE
Saving the flow vectors

### ISSUE THREAD

**Issue by nikky4D** [davidstutz/flow-io-opencv#3]
Hi 

Do you have code for saving the x,y as an image, not as a .txt file? I attempted a conversion to 32FC3, saving as a .bmp, which was unsuccessful, as I could not see the vectors clearly. 

My goal is to be able to use an imwrite for the images in opencv, or matlab or octave.

Thank you for any help you can give.

**Comment by davidstutz** [comment]
Sorry for the late reply. No there isn't code for that included. I think you cannot simply convert it, you have to loop over the flow field. Have a look at [Line 97](https://github.com/davidstutz/flow-io-opencv/blob/master/lib/flowIOOpenCVWrapper.cpp#L79). You can simply reverse the loop, given an `CFloatImage` you can write to the `cv::Mat` instead. However, the flow values are not meant to be written as an image. I would always recommend saving it using an OpenCV dump instead.
